version: 2

jobs:
  build:
    docker:
      - image: davidbohunek/rust-js:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache

      # Rust jobs
      - run:
          name: CORE formatting
          command: |
            rustfmt --version
            cd modules/core && cargo fmt --all -- --check
      - run:
          name: JS-BRIDGE formatting
          command: |
            rustfmt --version
            cd modules/js-bridge/native && cargo fmt --all -- --check
      - run:
          name: RUST-DEMO formatting
          command: |
            rustfmt --version
            cd apps/rust-demo && cargo fmt --all -- --check
      - run:
          name: CORE Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd modules/core && rustup run stable cargo build
      - run:
          name: RUST-DEMO Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd apps/rust-demo && rustup run stable cargo build
      - run:
          name: CORE Tests
          command: cd modules/core && rustup run stable cargo test

      #JS jobs
      - run: 
          name: JS-BRIDGE npm install
          command: |
            cd modules/js-bridge && npm install
      - run:
          name: JS-BRIDGE JS formatting
          command: |
            cd modules/js-bridge && npm run lint
      - run:
          name: JS-BRIDGE Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd modules/js-bridge && npm run build
      - run: 
          name: DESKTOP npm install
          command: |
            cd apps/desktop && npm install
      - run:
          name: DESKTOP formatting
          command: |
            cd apps/desktop && npm run lint
      - run:
          name: DESKTOP Build
          command: |
            cd apps/desktop && npm run build

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./modules/core/target"
            - "./modules/js-bridge/native/target"
            - "./apps/rust-demo/target"
