version: 2

jobs:
  build:
    docker:
    # need custom docker image with both Rust and NPM
      - image: davidbohunek/rust-js:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: CORE formatting
          command: |
            rustfmt --version
            cd modules/core && cargo fmt --all -- --check
      - run:
          name: JS-BRIDGE Rust formatting
          command: |
            rustfmt --version
            cd modules/js-bridge/native && cargo fmt --all -- --check
      - run:
          name: JS-BRIDGE JS formatting
          command: |
            cd modules/js-bridge && npm run lint
      - run:
          name: RUST-DEMO formatting
          command: |
            rustfmt --version
            cd apps/rust-demo && cargo fmt --all -- --check
      - run:
          name: CORE Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            cd modules/core && rustup run nightly cargo build
      - run:
          name: JS-BRIDGE Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            cd modules/js-bridge && npm run build
      - run:
          name: RUST-DEMO Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            cd apps/rust-demo && rustup run nightly cargo build
      - run:
          name: CORE Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd modules/core && rustup run stable cargo build
      - run:
          name: JS-BRIDGE Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd modules/js-bridge && npm run build
      - run:
          name: RUST-DEMO Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd apps/rust-demo && rustup run stable cargo build
      - run:
          name: CORE Tests
          command: cd modules/core && rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./modules/core/target"
            - "./modules/js-bridge/native/target"
            - "./apps/rust-demo/target"
            