[package]
name = "f1-laps-core"
version = "0.1.0"
authors = ["David Bohunek <bohunek@gmail.com>"]

[dependencies]
serde = "1.0.62"
serde_derive = "1.0.62"
bincode = "1.0.0"
chrono = "0.4.2"
lazy_static = "1.0.1"

[lib]
name = "f1_laps_core"
