#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Tick {
    pub session_time: f32,
    pub session_distance: f32,
    pub lap_number: u8,
    pub lap_time: f32,
    pub lap_distance: f32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub speed: f32,
    pub throttle: f32,
    pub steer: f32,
    pub brake: f32,
    pub gear: u8,
    pub rev_lights_percent: u8,
    pub tyres_wear: [u8; 4],
    pub car_position: u8,
    pub is_drs_open: bool,
    pub sector_number: u8,
    pub sector1_time: f32,
    pub sector2_time: f32,
    pub team_id: u8,
    pub total_laps: u8,
    pub last_lap_time: f32,
    pub max_gears: u8,
    pub session_type: u8,
    pub track_id: u8,
    pub vehicle_fia_flags: i8,
    pub era: u16,
    pub tyre_compound: u8,
    pub is_current_lap_valid: bool,
    pub is_spectating: bool,
    pub car_index: u8,
    pub cars_total: u8,
    pub cars: Vec<Car>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Car {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub last_lap_time: f32,
    pub current_lap_time: f32,
    pub best_lap_time: f32,
    pub driver_id: u8,
    pub team_id: u8,
    pub position: u8,
    pub tyre_compound: u8,
    pub sector_number: u8,
    pub sector1_time: f32,
    pub sector2_time: f32,
    pub is_current_lap_valid: bool,
    pub penalties: u8,
}
